### ISSUE TITLE
Trying to Build the desktop from the master branch gave me error

### ISSUE THREAD

**Issue by bytersproblem** [Laverna/laverna-desktop#3]
`Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from /home/borivoje/laverna-desktop-master/app/dist/images/icon/icon-120x120.png
    at new SystemTray (/home/user/laverna-desktop-master/app/SystemTray.js:16:21)
    at new App (/home/user/laverna-desktop-master/app/App.js:33:27)
    at App.app.on (/home/user/laverna-desktop-master/index.js:70:30)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:194:7)`

**Comment by bytersproblem** [comment]
The prebuild 0.7.3 version cannot connect to RemoteStorage server.

**Comment by LoveSponge** [comment]
You need to run
`npm install`
AND THEN
`npm run setup`

If this doesn't fix it for you, can you include more information as to what command you ran and the complete terminal output.
